export const feelings = [
  {label: "Flat", value: "flat"},
  {label: "Upset", value: "upset"},
  {label: "Abandoned", value: "abandoned"},
  {label: "Overwhelmed", value: "overwhelmed"},
  {label: "Distraught", value: "distraught"},
  {label: "Disappointed", value: "disappointed"},
  {label: "Desperate", value: "desperate"},
  {label: "Lonely", value: "lonely"},
  {label: "Irritable", value: "irritable"},
  {label: "Enraged", value: "enraged"},
  {label: "Scared", value: "scared"},
  {label: "Confused", value: "confused"},
  {label: "Weak", value: "weak"},
  {label: "Guilty", value: "guilty"},
  {label: "Apologetic", value: "apologetic"},
  {label: "Regretful", value: "regretful"},
  {label: "Restless", value: "restless"},
  {label: "Hateful", value: "hateful"},
  {label: "Paranoid", value: "paranoid"},
  {label: "Frightened", value: "frightened"},
  {label: "Panic-stricken", value: "panic-stricken"},
  {label: "Nervous", value: "nervous"},
  {label: "Shy", value: "shy"},
  {label: "Uncertain", value: "uncertain"},
  {label: "Doubtful", value: "doubtful"},
  {label: "Foggy", value: "foggy"},
  {label: "Grandiose", value: "grandiose"},
  {label: "Exhausted", value: "exhausted"},
  {label: "Uncontrollable energy", value: "uncontrollableenergy"},
  {label: "Anger", value: "anger"}
];
